/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.63
 * Generated at: 2021-04-27 05:54:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class seatsel_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    ");
Object name= session.getAttribute("name");
    if(name==null){
    
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("    alert('로그인 하세요.');\r\n");
      out.write("    location.href='index.jsp';\r\n");
      out.write("    </script>\r\n");
      out.write("    ");

    }
    
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/spro/css/mycss.css\">\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("$('document').ready(function(){\r\n");
      out.write("\t$('button').on('click',function(obj){\r\n");
      out.write("\t\t$('button').attr('class','btn btn-outline-success btn-block');\r\n");
      out.write("\t\t$(this).attr('class','btn btn-danger btn-block');\r\n");
      out.write("\t\t\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t$('#confirm').on('click',function(){\r\n");
      out.write("\t\tvar seat='';\r\n");
      out.write("\t\t$('button').each(function(index,obj){\t\t\r\n");
      out.write("\t\t\tif($(this).attr('class')=='btn btn-danger btn-block'){\r\n");
      out.write("\t\t\t\t//console.log(\"$(this).attr('class')=\"+$(this).attr('class'));\r\n");
      out.write("\t\t\t\t//console.log(\"$(this).text()=\"+$(this).text());\r\n");
      out.write("\t\t\t\tseat=$(this).text();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\tlocation.href='seatsave.jsp?seat='+seat;\r\n");
      out.write("\t})\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"jumbotron *\">\r\n");
      out.write("\r\n");
      out.write("<h1>좌석선택</h1>\r\n");
      out.write("<p>좌석을 선택하세요.</p>\r\n");
      out.write("<div class=\"row text-center\">\r\n");
      out.write("<div class=\"col-sm-2\"><button class=\"btn btn btn-outline-success btn-block\">\t1\t</button></div>\r\n");
      out.write("<div class=\"col-sm-2\"><button class=\"btn btn btn-outline-success btn-block\">\t2\t</button></div>\r\n");
      out.write("<div class=\"col-sm-2\"><button class=\"btn btn btn-outline-success btn-block\">\t3\t</button></div>\r\n");
      out.write("<div class=\"col-sm-2\"><button class=\"btn btn btn-outline-success btn-block\">\t4\t</button></div>\r\n");
      out.write("<div class=\"col-sm-2\"><button class=\"btn btn btn-outline-success btn-block\">\t5\t</button></div>\r\n");
      out.write("<div class=\"col-sm-2\"><button class=\"btn btn btn-outline-success btn-block\">\t6\t</button></div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"row text-center mt-2\">\r\n");
      out.write("<div class=\"col-sm-2\"><button class=\"btn btn btn-outline-success btn-block\">\t7\t</button></div>\r\n");
      out.write("<div class=\"col-sm-8\"></div>\r\n");
      out.write("<div class=\"col-sm-2\"><button class=\"btn btn btn-outline-success btn-block\">\t8\t</button></div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"row text-center mt-2\">\r\n");
      out.write("<div class=\"col-sm-2\"><button class=\"btn btn btn-outline-success btn-block\">\t9\t</button></div>\r\n");
      out.write("<div class=\"col-sm-1\"></div>\r\n");
      out.write("<div class=\"col-sm-2\"><button class=\"btn btn btn-outline-success btn-block\">\t10\t</button></div>\r\n");
      out.write("<div class=\"col-sm-2\"><button class=\"btn btn btn-outline-success btn-block\">\t11\t</button></div>\r\n");
      out.write("<div class=\"col-sm-2\"><button class=\"btn btn btn-outline-success btn-block\">\t12\t</button></div>\r\n");
      out.write("<div class=\"col-sm-1\"></div>\r\n");
      out.write("<div class=\"col-sm-2\"><button class=\"btn btn btn-outline-success btn-block\">\t13\t</button></div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"row text-center mt-2\">\r\n");
      out.write("<div class=\"col-sm-2\"><button class=\"btn btn btn-outline-success btn-block\">\t14\t</button></div>\r\n");
      out.write("<div class=\"col-sm-1\"></div>\r\n");
      out.write("<div class=\"col-sm-2\"><button class=\"btn btn btn-outline-success btn-block\">\t15\t</button></div>\r\n");
      out.write("<div class=\"col-sm-2\"><button class=\"btn btn btn-outline-success btn-block\">\t16\t</button></div>\r\n");
      out.write("<div class=\"col-sm-2\"><button class=\"btn btn btn-outline-success btn-block\">\t17\t</button></div>\r\n");
      out.write("<div class=\"col-sm-1\"></div>\r\n");
      out.write("<div class=\"col-sm-2\"><button class=\"btn btn btn-outline-success btn-block\">\t18\t</button></div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"row text-center mt-2\">\r\n");
      out.write("<div class=\"col-sm-2\"><button class=\"btn btn btn-outline-success btn-block\">\t19\t</button></div>\r\n");
      out.write("<div class=\"col-sm-8\"></div>\r\n");
      out.write("<div class=\"col-sm-2\"><button class=\"btn btn btn-outline-success btn-block\">\t20\t</button></div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"row text-center mt-2\">\r\n");
      out.write("<div class=\"col-sm-2\"><button class=\"btn btn btn-outline-success btn-block\">\t21\t</button></div>\r\n");
      out.write("<div class=\"col-sm-2\"><button class=\"btn btn btn-outline-success btn-block\">\t22\t</button></div>\r\n");
      out.write("<div class=\"col-sm-2\"><button class=\"btn btn btn-outline-success btn-block\">\t23\t</button></div>\r\n");
      out.write("<div class=\"col-sm-2\"><button class=\"btn btn btn-outline-success btn-block\">\t24\t</button></div>\r\n");
      out.write("<div class=\"col-sm-2\"><button class=\"btn btn btn-outline-success btn-block\">\t25\t</button></div>\r\n");
      out.write("<div class=\"col-sm-2\"><button class=\"btn btn btn-outline-success btn-block\">\t26\t</button></div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"row text-center mt-5\">\r\n");
      out.write("<div class=\"col-sm-4\"></div>\r\n");
      out.write("<div class=\"col-sm-2\"><input type=\"button\" id=\"confirm\" class=\"btn btn btn-info btn-block\" value=\"확인\"/>\t</div>\r\n");
      out.write("<div class=\"col-sm-1\"></div>\r\n");
      out.write("<div class=\"col-sm-2\"><input type=\"button\" id=\"cencel\" class=\"btn btn btn-info btn-block\" value=\"취소\"/>\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
